import {
  IsString,
  IsNotEmpty,
  IsOptional,
  IsEnum,
  IsUUID,
  IsNumber,
  IsArray,
  ValidateNested,
  IsDateString,
  IsBoolean,
  MaxLength,
} from 'class-validator';
import { PartialType } from '@nestjs/mapped-types';
import { Type } from 'class-transformer';
import { JournalEntryType, JournalEntryStatus } from '@common/enums';
import { PartyType } from '@/entities/tenant';

export class CreateJournalEntryLineDto {
  @IsNumber()
  lineNumber: number;

  @IsUUID()
  accountId: string;

  @IsUUID()
  @IsOptional()
  costCenterId?: string;

  @IsString()
  @IsOptional()
  @MaxLength(500)
  description?: string;

  @IsNumber()
  @Type(() => Number)
  debitAmount: number;

  @IsNumber()
  @Type(() => Number)
  creditAmount: number;

  @IsString()
  @IsOptional()
  @MaxLength(3)
  currency?: string;

  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  exchangeRate?: number;

  @IsEnum(PartyType)
  @IsOptional()
  partyType?: PartyType;

  @IsUUID()
  @IsOptional()
  partyId?: string;

  @IsUUID()
  @IsOptional()
  taxCategoryId?: string;
}

export class CreateJournalEntryDto {
  @IsDateString()
  entryDate: string;

  @IsUUID()
  fiscalYearId: string;

  @IsUUID()
  fiscalPeriodId: string;

  @IsEnum(JournalEntryType)
  @IsOptional()
  entryType?: JournalEntryType;

  @IsString()
  @IsOptional()
  @MaxLength(50)
  referenceType?: string;

  @IsUUID()
  @IsOptional()
  referenceId?: string;

  @IsString()
  @IsOptional()
  @MaxLength(50)
  referenceNumber?: string;

  @IsString()
  @IsNotEmpty()
  description: string;

  @IsString()
  @IsOptional()
  @MaxLength(3)
  currency?: string;

  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  exchangeRate?: number;

  @IsString()
  @IsOptional()
  notes?: string;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => CreateJournalEntryLineDto)
  lines: CreateJournalEntryLineDto[];
}

export class UpdateJournalEntryDto extends PartialType(CreateJournalEntryDto) {}

export class PostJournalEntryDto {
  @IsUUID()
  id: string;
}

export class ReverseJournalEntryDto {
  @IsDateString()
  reversalDate: string;

  @IsString()
  @IsOptional()
  description?: string;
}

export class QueryJournalEntryDto {
  @IsOptional()
  @IsEnum(JournalEntryType)
  entryType?: JournalEntryType;

  @IsOptional()
  @IsEnum(JournalEntryStatus)
  status?: JournalEntryStatus;

  @IsOptional()
  @IsUUID()
  fiscalYearId?: string;

  @IsOptional()
  @IsUUID()
  fiscalPeriodId?: string;

  @IsOptional()
  @IsDateString()
  startDate?: string;

  @IsOptional()
  @IsDateString()
  endDate?: string;

  @IsOptional()
  @IsUUID()
  accountId?: string;

  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  isAutoGenerated?: boolean;

  @IsOptional()
  @IsString()
  search?: string;

  @IsOptional()
  @Type(() => Number)
  page?: number;

  @IsOptional()
  @Type(() => Number)
  limit?: number;
}
