import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  OneToMany,
  JoinColumn,
} from 'typeorm';
import { JournalEntryType, JournalEntryStatus } from '@common/enums';
import { FiscalYear } from './fiscal-year.entity';
import { FiscalPeriod } from './fiscal-period.entity';
import { JournalEntryLine } from './journal-entry-line.entity';

@Entity('journal_entries')
export class JournalEntry {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'entry_number', length: 50, unique: true })
  entryNumber: string;

  @Column({ name: 'entry_date', type: 'date' })
  entryDate: Date;

  @Column({ name: 'fiscal_year_id' })
  fiscalYearId: string;

  @Column({ name: 'fiscal_period_id' })
  fiscalPeriodId: string;

  @Column({
    name: 'entry_type',
    type: 'enum',
    enum: JournalEntryType,
    default: JournalEntryType.MANUAL,
  })
  entryType: JournalEntryType;

  @Column({ name: 'reference_type', length: 50, nullable: true })
  referenceType: string;

  @Column({ name: 'reference_id', nullable: true })
  referenceId: string;

  @Column({ name: 'reference_number', length: 50, nullable: true })
  referenceNumber: string;

  @Column({ type: 'text' })
  description: string;

  @Column({
    name: 'total_debit',
    type: 'decimal',
    precision: 18,
    scale: 4,
    default: 0,
  })
  totalDebit: number;

  @Column({
    name: 'total_credit',
    type: 'decimal',
    precision: 18,
    scale: 4,
    default: 0,
  })
  totalCredit: number;

  @Column({ length: 3, default: 'BDT' })
  currency: string;

  @Column({
    name: 'exchange_rate',
    type: 'decimal',
    precision: 12,
    scale: 6,
    default: 1,
  })
  exchangeRate: number;

  @Column({
    type: 'enum',
    enum: JournalEntryStatus,
    default: JournalEntryStatus.DRAFT,
  })
  status: JournalEntryStatus;

  @Column({ name: 'is_auto_generated', type: 'tinyint', default: 0 })
  isAutoGenerated: boolean;

  @Column({ name: 'reversal_of_id', nullable: true })
  reversalOfId: string;

  @Column({ name: 'reversed_by_id', nullable: true })
  reversedById: string;

  @Column({ name: 'posted_by', nullable: true })
  postedBy: string;

  @Column({ name: 'posted_at', type: 'timestamp', nullable: true })
  postedAt: Date;

  @Column({ type: 'text', nullable: true })
  notes: string;

  @Column({ name: 'created_by', nullable: true })
  createdBy: string;

  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;

  // Relations
  @ManyToOne(() => FiscalYear)
  @JoinColumn({ name: 'fiscal_year_id' })
  fiscalYear: FiscalYear;

  @ManyToOne(() => FiscalPeriod)
  @JoinColumn({ name: 'fiscal_period_id' })
  fiscalPeriod: FiscalPeriod;

  @ManyToOne(() => JournalEntry)
  @JoinColumn({ name: 'reversal_of_id' })
  reversalOf: JournalEntry;

  @OneToMany(() => JournalEntryLine, (line) => line.journalEntry)
  lines: JournalEntryLine[];

  // Helper
  get isBalanced(): boolean {
    return Math.abs(this.totalDebit - this.totalCredit) < 0.01;
  }
}
